table dim_date
	lineageTag: 00ca6363-7054-4da0-8df6-c815ae8db9a1

	column date
		dataType: dateTime
		formatString: Mmm yy
		lineageTag: d7323495-574d-48a1-8ca4-b22e62fdd03e
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 3339830a-604d-439f-9c54-97e2d6a55a04
			defaultHierarchy: LocalDateTable_3f090381-6c9f-4972-8129-9fee5d724046.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column Month
		dataType: dateTime
		formatString: Mmm yy
		lineageTag: 198c46ed-a5b0-42f8-8ab2-2149034c9b81
		summarizeBy: none
		sourceColumn: Month

		variation Variation
			isDefault
			relationship: 85eec89e-0bcb-47a7-ab6c-bcfc29585908
			defaultHierarchy: LocalDateTable_9c5c2fcc-ccb3-4b95-a7f4-6a1ec85193d5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Fiscal Year'
		dataType: string
		lineageTag: eee71b00-c0a5-4425-9f03-274d2eb525e4
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column FY_month_num = MONTH(DATE(YEAR(dim_date[date]),MONTH(dim_date[date])+4,1))
		formatString: 0
		lineageTag: fba3467f-f3a6-4734-abb4-e3f19bf64ea7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Quarter = "Q" & ROUNDUP(dim_date[FY_month_num]/3,0)
		lineageTag: a8299128-43b3-4f37-a987-8deb191c4116
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column YTD_YTG = ```
			
			var last_sales_date=MAX(Last_Sales_Month[Last_Sales_Month])
			var FY_month_num=MONTH(DATE(YEAR(last_sales_date),MONTH(last_sales_date)+4,1))
			RETURN
			IF(dim_date[FY_month_num]>FY_month_num,"YTG","YTD")
			
			```
		lineageTag: ba134107-543f-4bb0-bda3-4c1e611141fc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = {Number.From(#date(2017,9,1))..Number.From(#date(2022,12,31))},
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Column1", Order.Ascending}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Sorted Rows",{{"Column1", "date"}}),
				    #"Inserted Start of Month" = Table.AddColumn(#"Renamed Columns", "Start of Month", each Date.StartOfMonth([date]), type date),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Start of Month",{{"Start of Month", "Month"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "Fiscal Year", each Date.Year(Date.AddMonths([Month],4))),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Fiscal Year", type text}}),
				    #"Unchecked 2023 from ""Fiscal Year""" = Table.SelectRows(#"Changed Type1", each ([Fiscal Year] <> "2023"))
				in
				    #"Unchecked 2023 from ""Fiscal Year"""

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

