table dim_customer
	lineageTag: 96a056b5-61bc-4591-be9c-c6a004106325

	column customer
		dataType: string
		lineageTag: 05323bf0-8dd5-4277-9cc8-2e1b26729e7c
		summarizeBy: none
		sourceColumn: customer

		annotation SummarizationSetBy = Automatic

	column market
		dataType: string
		lineageTag: 35713279-afc5-4926-a7a3-c7ac1d94924b
		summarizeBy: none
		sourceColumn: market

		annotation SummarizationSetBy = Automatic

	column platform
		dataType: string
		lineageTag: 78193499-223f-4c33-bbbc-efab2db2f715
		summarizeBy: none
		sourceColumn: platform

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: e94a5c81-0dbb-4c2f-9d0e-d18b753138df
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column customer_code
		dataType: string
		lineageTag: 56d0cbc5-90ab-475f-8ef7-7ff9f74d83d0
		summarizeBy: none
		sourceColumn: customer_code

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = MySQL.Database("localhost", "gdb041", [ReturnSingleDatabase=true]),
				    gdb041_dim_customer = Source{[Schema="gdb041",Item="dim_customer"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(gdb041_dim_customer,"AltiQ Exclusive","AtliQ Exclusive",Replacer.ReplaceText,{"customer"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Atliq Exclusive","AtliQ Exclusive",Replacer.ReplaceText,{"customer"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",each [channel], each if [customer_code]="90002011" then "Direct" else [Channel],Replacer.ReplaceText,{"channel"}),
				    #"Trimmed Text" = Table.TransformColumns(#"Replaced Value2",{{"customer", Text.Trim, type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Trimmed Text", each true),
				    #"Replaced Value3" = Table.ReplaceValue(#"Filtered Rows","USA","United States",Replacer.ReplaceText,{"market"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Newzealand","New Zealand",Replacer.ReplaceText,{"market"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Philiphines","Philippines",Replacer.ReplaceText,{"market"})
				in
				    #"Replaced Value5"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

