table dim_market
	lineageTag: b7cd1136-f56d-4e4a-87f9-82902e10613f

	column market
		dataType: string
		lineageTag: e9a1a670-8c29-4d6d-a03e-23edf439613e
		summarizeBy: none
		sourceColumn: market

		annotation SummarizationSetBy = Automatic

	column sub_zone
		dataType: string
		lineageTag: e0681e71-bba8-4356-9d4a-686e1471f7c4
		summarizeBy: none
		sourceColumn: sub_zone

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 93a730b8-09c3-4975-8f87-961fd8d30a30
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition dim_market = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = MySQL.Database("localhost", "gdb041", [ReturnSingleDatabase=true]),
				    gdb041_dim_market = Source{[Schema="gdb041",Item="dim_market"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(gdb041_dim_market,"nan","NA",Replacer.ReplaceText,{"sub_zone", "region"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Newzealand","New Zealand",Replacer.ReplaceText,{"market"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Philiphines","Philippines",Replacer.ReplaceText,{"market"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","USA","United States",Replacer.ReplaceText,{"market"})
				in
				    #"Replaced Value3"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

