table fact_sales_monthly
	lineageTag: 07da31c7-aa86-4dec-830f-aece9ebc597b

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 21f1ee78-7662-40f8-8aa0-4abd4ab1e3e8
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 4031eab4-90a8-4675-9fde-081dd9ccb767
			defaultHierarchy: LocalDateTable_8afa8047-5804-4e97-95d3-c29e63212b55.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column product_code
		dataType: string
		lineageTag: f2e6bc1a-abb7-4db5-84df-a717a014d9c8
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = Automatic

	column customer_code
		dataType: string
		lineageTag: 6e5cee6d-f15d-4d5c-b7a9-e02f685161c3
		summarizeBy: none
		sourceColumn: customer_code

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: int64
		formatString: 0
		lineageTag: a3584004-b15e-4495-8dc3-22fd008ddf8a
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	partition fact_sales_monthly = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Source = MySQL.Database("localhost", "gdb041", [ReturnSingleDatabase=true]),
				    gdb041_fact_sales_monthly = Source{[Schema="gdb041",Item="fact_sales_monthly"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(gdb041_fact_sales_monthly,{{"sold_quantity", "Qty"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"date", "product_code", "customer_code", "Qty"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

