table fact_forecast_monthly
	lineageTag: 8e4432c3-269a-4030-a845-8ebb0f7fad8e

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c466f86-ef52-4a0f-b4fa-5e5b5d7f0b69
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column product_code
		dataType: string
		lineageTag: 61a0caf0-a5bf-4f1e-9138-f72168657b80
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = Automatic

	column customer_code
		dataType: string
		lineageTag: 2499686c-382e-496c-89d6-6f69e5115927
		summarizeBy: none
		sourceColumn: customer_code

		annotation SummarizationSetBy = Automatic

	column forecast_quantity
		dataType: int64
		formatString: 0
		lineageTag: b0a5909a-59e6-4fa9-8f84-127635976598
		summarizeBy: sum
		sourceColumn: forecast_quantity

		annotation SummarizationSetBy = Automatic

	partition fact_forecast_monthly = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Source = MySQL.Database("localhost", "gdb041", [ReturnSingleDatabase=true]),
				    gdb041_fact_forecast_monthly = Source{[Schema="gdb041",Item="fact_forecast_monthly"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(gdb041_fact_forecast_monthly,{"date", "product_code", "customer_code", "forecast_quantity"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

