table Facts_Actuals_Estimate
	lineageTag: 29b27d5c-0858-4f23-9ede-eeacb96f7b4d

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 80523332-7fbb-43aa-820b-8ffad024cef8
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column product_code
		dataType: string
		lineageTag: 8d2e0dce-c966-40be-aef9-80b132bcbf7e
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = Automatic

	column customer_code
		dataType: string
		lineageTag: 8ddb9a0a-abf6-4247-af5e-ca4ec4916125
		summarizeBy: none
		sourceColumn: customer_code

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: int64
		formatString: 0
		lineageTag: e13e6836-cac5-4f71-bc01-c4efddbb4c13
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: string
		lineageTag: fc075beb-e5b3-471f-98f4-a58f9524365f
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column gross_sales_amount
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ca94497a-e4e0-4f7f-b76b-41c806d36ba5
		summarizeBy: sum
		sourceColumn: gross_sales_amount

		annotation SummarizationSetBy = Automatic

	column net_invoice_sales_amount
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 692970ae-8f38-4ccf-b52d-24e85241f9f4
		summarizeBy: sum
		sourceColumn: net_invoice_sales_amount

		annotation SummarizationSetBy = Automatic

	column post_invoice_deduction_amount = ```
			
			var res = CALCULATE(MAX(post_invoice_deductions[discounts_pct]), 
			RELATEDTABLE(post_invoice_deductions))
			RETURN res*Facts_Actuals_Estimate[net_invoice_sales_amount]
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7c2e8497-0640-4c2c-bac8-14a7968a9567
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column post_invoice_other_deduction_amount = ```
			
			var res = CALCULATE(MAX(post_invoice_deductions[other_deductions_pct]), 
			RELATEDTABLE(post_invoice_deductions))
			RETURN res*Facts_Actuals_Estimate[net_invoice_sales_amount]
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ab879c07-7008-4bc3-a136-8f19a8f39694
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column net_sales = Facts_Actuals_Estimate[net_invoice_sales_amount]-Facts_Actuals_Estimate[post_invoice_deduction_amount]-Facts_Actuals_Estimate[post_invoice_other_deduction_amount]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c8f7de0c-5e64-4ed9-af0b-77b5ce873769
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column manufacturing_cost =
			
			var res=CALCULATE(MAX(manufacturing_cost[manufacturing_cost]),RELATEDTABLE(manufacturing_cost))
			RETURN res*Facts_Actuals_Estimate[Qty]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a69acd98-c33c-44eb-82b7-42469f1efe40
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column freight_cost =
			
			var res = CALCULATE(MAX(freight_cost[freight_pct]),
			RELATEDTABLE(freight_cost))
			RETURN res*Facts_Actuals_Estimate[net_sales]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 098ffad5-8968-4c56-8aa3-63c9a89fdfc1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column freight_other_cost =
			
			var res = CALCULATE(MAX(freight_cost[other_cost_pct]),
			RELATEDTABLE(freight_cost))
			RETURN res*Facts_Actuals_Estimate[net_sales]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 72fa0b49-ad5f-48e0-b7b7-253e821be8b6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ads_promotion =
			
			var res = CALCULATE(MAX(Operational_Expense[ads_promotions_pct]),
			RELATEDTABLE(Operational_Expense))
			RETURN res*Facts_Actuals_Estimate[net_sales]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 855e8f55-4dd2-4ef9-9b25-662c64d6e2f8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column other_operational_expense =
			
			var res = CALCULATE(MAX(Operational_Expense[other_operational_expense_pct]),
			RELATEDTABLE(Operational_Expense))
			RETURN res*Facts_Actuals_Estimate[net_sales]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 6baa327a-29cb-45aa-9df6-e58b22645808
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Facts_Actuals_Estimate = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Source = Table.Combine({fact_sales_monthly, Remaining_forecast}),
				    #"Filtered Rows" = Table.SelectRows(Source, each true),
				    #"Added Custom Column ""Fiscal_Year""" = Table.AddColumn(#"Filtered Rows", "Fiscal_Year", each Date.Year(Date.AddMonths([date],4))),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Added Custom Column ""Fiscal_Year""", {"Fiscal_Year"}),
				    #"Renamed to ""fiscal_year""" = Table.RenameColumns(#"Removed Errors",{{"Fiscal_Year", "fiscal_year"}}),
				    #"Changed Type to text" = Table.TransformColumnTypes(#"Renamed to ""fiscal_year""",{{"fiscal_year", type text}}),
				    #"Merged Queries(fact_sales_monthly with gdb056 gross_price table)" = Table.NestedJoin(#"Changed Type to text", {"product_code", "fiscal_year"}, gross_price, {"product_code", "fiscal_year"}, "gdb056 gross_price", JoinKind.LeftOuter),
				    #"Expanded gdb056 gross_price" = Table.ExpandTableColumn(#"Merged Queries(fact_sales_monthly with gdb056 gross_price table)", "gdb056 gross_price", {"gross_price"}, {"gross_price"}),
				    #"Changed Type to fixed decimal number" = Table.TransformColumnTypes(#"Expanded gdb056 gross_price",{{"gross_price", Currency.Type}}),
				    #"Added Custom ""gross_price_amount""" = Table.AddColumn(#"Changed Type to fixed decimal number", "gross_price_amount", each [gross_price]*[Qty]),
				    #"Changed Type fixed decimal number)" = Table.TransformColumnTypes(#"Added Custom ""gross_price_amount""",{{"gross_price_amount", Currency.Type}}),
				    #"Merged Queries(facts_sales_monthly and gdb056 pre_invoice_deductions)" = Table.NestedJoin(#"Changed Type fixed decimal number)", {"customer_code", "fiscal_year"}, pre_invoice_deductions, {"customer_code", "fiscal_year"}, "gdb056 pre_invoice_deductions", JoinKind.LeftOuter),
				    #"Expanded gdb056 pre_invoice_deductions" = Table.ExpandTableColumn(#"Merged Queries(facts_sales_monthly and gdb056 pre_invoice_deductions)", "gdb056 pre_invoice_deductions", {"pre_invoice_discount_pct"}, {"pre_invoice_discount_pct"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Expanded gdb056 pre_invoice_deductions",{{"pre_invoice_discount_pct", Percentage.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type3",{{"gross_price_amount", "gross_sales_amount"}}),
				    #"Added Custom2" = Table.AddColumn(#"Renamed Columns1", "pre_invoice_discount_amount", each [gross_sales_amount]*[pre_invoice_discount_pct]),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom2",{{"pre_invoice_discount_amount", Currency.Type}}),
				    #"Added Custom3" = Table.AddColumn(#"Changed Type4", "net_invoice_sales_amount", each [gross_sales_amount]-[pre_invoice_discount_amount]),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom3",{{"net_invoice_sales_amount", Currency.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type5",{"gross_price", "pre_invoice_discount_pct", "pre_invoice_discount_amount"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

