table 'Last Refresh Date'
	lineageTag: 38daf125-be18-42d6-8628-f0243535f37b

	column 'Last Refersh Date Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 144542cf-d557-45fb-a793-90c19901c820
		summarizeBy: none
		sourceColumn: Last Refersh Date Time

		variation Variation
			isDefault
			relationship: 43720fe8-0c74-421a-9542-7d02d2ffe29c
			defaultHierarchy: LocalDateTable_de016037-91ec-4420-9167-bf136eaeaab8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e347a62c-f849-4514-85bc-49697499c922
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: e5bbb3e9-7263-405a-a3ba-c8c9976f1e82
			defaultHierarchy: LocalDateTable_84281438-e0df-410f-8f6d-5808add2c759.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 1d18bd4e-1ac2-4b29-bf46-edb039fd1b3b
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Last Refresh Date' = m
		mode: import
		source =
				let
				    Source = DateTime.LocalNow(),
				    #"Converted to Table" = #table(1, {{Source}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type datetime}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Last Refersh Date Time"}}),
				    #"Inserted Date" = Table.AddColumn(#"Renamed Columns", "Date", each DateTime.Date([Last Refersh Date Time]), type date),
				    #"Inserted Time" = Table.AddColumn(#"Inserted Date", "Time", each DateTime.Time([Last Refersh Date Time]), type time)
				in
				    #"Inserted Time"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

