table marketshare
	lineageTag: d405bdd0-1354-4c97-a932-d88424c842d7

	column sub_zone
		dataType: string
		lineageTag: 3f327325-3715-429e-8896-faa7c04f999a
		summarizeBy: none
		sourceColumn: sub_zone

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 31668e63-1197-4ba2-acd1-6bf64f669972
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column fy
		dataType: string
		lineageTag: 931b3e02-e756-489b-a109-67eb62cc2d4a
		summarizeBy: none
		sourceColumn: fy

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column total_market_sales_$
		dataType: double
		lineageTag: c31f8d26-654b-4cfc-96f9-38986628ec6f
		summarizeBy: sum
		sourceColumn: total_market_sales_$

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column manufacturer
		dataType: string
		lineageTag: cb75e83a-8234-4735-8990-4e0e6fb3188b
		summarizeBy: none
		sourceColumn: manufacturer

		annotation SummarizationSetBy = Automatic

	column 'sales $'
		dataType: double
		lineageTag: 8ca41152-0583-4f21-a9e2-1abf0b49c094
		summarizeBy: sum
		sourceColumn: sales $

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition marketshare = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\DATA_ANALYST BOOTCAMP\Power BI\marketshare-v2022.xlsx"), null, true),
				    marketshare_Table = Source{[Item="marketshare",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(marketshare_Table,{{"sub_zone", type text}, {"category", type text}, {"fy_desc", Int64.Type}, {"total_market_sales_$", type number}, {"atliq_sales_$", type number}, {"dale_sales_$", type number}, {"innovo_sales_$", type number}, {"pacer_sales_$", type number}, {"bp_sales_$", type number}, {"others_sales_$", type number}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"sub_zone", "category", "fy_desc", "total_market_sales_$"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "manufacturer"}, {"Value", "sales $"}}),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Renamed Columns", {{"manufacturer", each Text.BeforeDelimiter(_, "_"), type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Extracted Text Before Delimiter",{{"fy_desc", "fy"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

