table NsGmTarget
	lineageTag: 15a2b6bb-6505-4c65-b472-f5b024d28a7d

	column market
		dataType: string
		lineageTag: 5cd68ab6-c4d5-4b93-9c86-652f75cf934a
		summarizeBy: none
		sourceColumn: market

		annotation SummarizationSetBy = Automatic

	column month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 498388ee-bd92-4354-96ee-1244b8534f93
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ns_target
		dataType: double
		lineageTag: 27974aec-e5d3-42c0-8459-82ef14f77851
		summarizeBy: sum
		sourceColumn: ns_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gm_target
		dataType: double
		lineageTag: 5f5da6f1-fde3-48ae-951d-c7366bbbbd47
		summarizeBy: sum
		sourceColumn: gm_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column np_target
		dataType: double
		lineageTag: d31f5002-1732-4cd7-b0b4-8edf8020100d
		summarizeBy: sum
		sourceColumn: np_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition NsGmTarget = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\DATA_ANALYST BOOTCAMP\Power BI\targets.xlsx"), null, true),
				    NsGmTarget_Sheet = Source{[Item="NsGmTarget",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(NsGmTarget_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"market", type text}, {"month", type date}, {"ns_target", type number}, {"gm_target", type number}, {"np_target", type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Newzealand","New Zealand",Replacer.ReplaceText,{"market"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","USA","United States",Replacer.ReplaceText,{"market"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Philiphines","Philippines",Replacer.ReplaceText,{"market"})
				in
				    #"Replaced Value2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

