table 'Set BM'
	lineageTag: 1908e365-92e6-48e0-b81d-957a7ab3f9d9

	column Benchmarks
		dataType: string
		lineageTag: 3f482170-557a-402b-b116-41b1ba5501de
		summarizeBy: none
		sourceColumn: Benchmarks

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 06e3bb8d-01c3-408b-94a7-798358c7f57d
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition 'Set BM' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WKitW8IlU0lEyVIrVAfNCEovSU0uAIkZKsbEA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Benchmarks = _t, ID = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Benchmarks", type text}, {"ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

